In [1]:
import numpy as np

In [3]:
e1 = np.array([1, 0])
e2 = np.array([0, 1])

In [5]:
u = 9*np.array([np.cos(0.4), np.sin(0.4)])
print(u)

[8.28954895 3.50476508]


In [6]:
v = 5*np.array([np.cos(0.15), np.sin(0.15)])
print(v)

[4.94385539 0.74719066]


In [9]:
9*5*np.cos(0.4-0.15)

43.60105897697901

In [10]:
u.dot(v)

43.60105897697901

In [24]:
u = np.array([7, 9])
v = np.array([7, 8])

In [16]:
np.linalg.norm(u)

11.40175425099138

In [17]:
np.arctan2(u[1], u[0])

0.9097531579442097

In [18]:
np.linalg.norm(v)

10.63014581273465

In [19]:
np.arctan2(v[1], v[0])

0.8519663271732721

In [25]:
e1t = np.array([6, 0])
e2t = np.array([0, 7])

In [29]:
u1t = u.dot(e1t/np.linalg.norm(e1t))/np.linalg.norm(e1t)
u2t = u.dot(e2t/np.linalg.norm(e2t))/np.linalg.norm(e2t)
u1t*e1t + u2t*e2t
print(u1t, u2t)

1.1666666666666667 1.2857142857142858


In [31]:
v1t = v.dot(e1t/np.linalg.norm(e1t))/np.linalg.norm(e1t)
v2t = v.dot(e2t/np.linalg.norm(e2t))/np.linalg.norm(e2t)
v1t*e1t + v2t*e2t
print(v1t, v2t)

1.1666666666666667 1.1428571428571428


In [33]:
np.sum(u1t*v1t + u2t*v2t)

2.8304988662131523

In [34]:
np.linalg.norm(u)*np.linalg.norm(v)*np.cos(np.abs(np.arctan2(u[1], u[0]) - np.arctan2(v[1], v[0])))

121.0

In [4]:
u = np.array([8, 0])
v = np.array([3, 7])
np.linalg.norm(u)*np.linalg.norm(v)*np.sin(np.arctan2(v[1], v[0]))

56.00000000000001

In [5]:
u = np.array([9, 5, 3])
np.linalg.norm(u)*np.linalg.norm(u)*np.sin(0.0)

0.0

In [11]:
v = np.array([2, 6, 5])
np.cross(u, v)
print(np.cross(u, v), np.cross(v, u))

[  7 -39  44] [ -7  39 -44]


In [9]:
w = np.array([8, 6, 2])
np.cross(w, u + v)

array([ 26, -42,  22])

In [10]:
np.cross(w, u) + np.cross(w, v)

array([ 26, -42,  22])

In [17]:
u = np.array([1, 0])
v = np.array([6, 3])

In [18]:
np.arccos(u.dot(v)/(np.linalg.norm(u)*np.linalg.norm(v)))

0.46364760900080615

In [19]:
w = np.array([6, -3])
np.arccos(u.dot(w)/(np.linalg.norm(u)*np.linalg.norm(w)))

0.46364760900080615

In [15]:
np.arctan2(np.linalg.norm(np.cross(u, v)), u.dot(v))

0.4636476090008061

In [16]:
np.arctan2(np.linalg.norm(np.cross(u, w)), u.dot(w))

0.4636476090008061

In [20]:
2*22/7 - 0.4636

5.822114285714285

In [21]:
a = np.array([5, -8, 0])
b = np.array([5, 8, 0])
c = np.array([0, 0, 8])
d = np.array([0, 0, -7])
ac = c - a
ad = d - a

In [24]:
n2 = np.cross(ac, ad)
n2 = n2/np.linalg.norm(n2)
print(n2)

[-0.8479983  -0.52999894  0.        ]


In [25]:
dc = c - d
db = b - d
n1 = np.cross(dc, db)
n1 = n1/np.linalg.norm(n1)
print(n1)

[-0.8479983   0.52999894  0.        ]


In [26]:
np.arctan2(np.linalg.norm(np.cross(n1, n2)), n1.dot(n2))

1.1171986306871249

In [41]:
np.arctan2(np.linalg.norm(np.cross(n2, n1)), n1.dot(n2))

1.1171986306871249

In [27]:
np.arccos(n1.dot(n2))

1.1171986306871249

In [29]:
np.arcsin(np.cross(n1, n2))

array([0.        , 0.        , 1.11719863])

In [31]:
u = np.array([9, 8, 2])
v = np.array([2, 6, 0])

In [32]:
u.dot(v)

66

In [33]:
np.linalg.norm(np.cross(u, v))

40.049968789001575

In [35]:
theta = np.arccos(u.dot(v)/(np.linalg.norm(u)*np.linalg.norm(v)))
print(theta)

0.5454174469098062


In [36]:
1/np.tan(theta)

1.6479413591484438

In [37]:
u.dot(v)/np.linalg.norm(np.cross(u, v))

1.6479413591484435

In [38]:
u = np.array([3,9,8])
a = np.array([8,3,8])
uh = np.array([[0, -u[2], u[1]],
               [u[2], 0, -u[0]],
               [-u[1], u[0], 0]])

In [39]:
print(uh.dot(a), np.cross(u, a))

[ 48  40 -63] [ 48  40 -63]


In [40]:
uh.T.dot(a)

array([-48, -40,  63])

In [42]:
u = np.array([7,6,5])
v = np.array([2,3,5])
w = np.array([3,7,4])

In [43]:
u.dot(np.cross(v, u))

0

In [44]:
u.dot(np.cross(v, w))

-94

In [45]:
v.dot(np.cross(u, w))

94

In [46]:
np.cross(u, np.cross(v, w))

array([  -5, -150,  187])

In [47]:
v*u.dot(w) - w*u.dot(v)

array([  -5, -150,  187])

In [2]:
xu = lambda u: np.array([3*np.cos(7*u[1]), 5*u[0]**2])
yu = lambda u: np.array([7, 2*(u[0]**2 + u[1]**2)])

In [3]:
zu = lambda xu, yu: lambda u: xu(u) + yu(u)

In [4]:
zu(xu, yu)([0.8, 0.6])

array([5.52921754, 5.2       ])

In [5]:
9*zu(xu, yu)([0.4, 0.7])

array([68.03583397, 18.9       ])

In [8]:
def x(u):
    return np.array([3*np.cos(7*u[1]), 5*u[0]**2]);
def y(u):
    return np.array([7, 2*(u[0]**2 + u[1]**2)]);
def z(u):
    return x(u) + y(u);
z([0.8, 0.6])

array([5.52921754, 5.2       ])

In [9]:
x = lambda u: np.array([3*u[0], 2*u[1], 1])
y = lambda u: np.array([-2*u[1], 3*u[0], u[2]])
f = lambda x, y: lambda u: x(u).dot(y(u))

In [10]:
f(x, y)(np.array([4, 3, 7]))

7

In [11]:
f(x, y)(np.array([8, 2, 5]))

5

In [12]:
z = lambda x, y: lambda u: np.cross(x(u), y(u))

In [13]:
z(x, y)(np.array([7, 6, 9]))

array([  87, -201,  585])

In [14]:
delf = lambda x, y: np.array([4*x - 2*y*np.sin(2*x),
                             np.cos(2*x)])
delf(5, 9)

array([29.79238   , -0.83907153])

In [17]:
delg = lambda x, y, z: np.array([2*y + 8*z, 2*x + 2*z, 2*y + 8*x])
delg(4, 5, 8)

array([74, 24, 42])

In [18]:
delh = lambda x: 1/x -3/(x**2)
delh(8)

0.078125