In [1]:
import numpy as np

In [3]:
u = np.array([8,3])
v = np.array([9,5])

In [4]:
a = 6
b = 7

In [5]:
u + v

array([17,  8])

In [6]:
b*u

array([56, 21])

In [7]:
a*u - b*v

array([-15, -17])

In [9]:
u = np.array([7,9,7])
v = np.array([8,8,3])

In [10]:
u - v

array([-1,  1,  4])

In [12]:
u + 7*v

array([63, 65, 28])

In [13]:
p = lambda x: 7*x**2 + 9*x + 7

In [14]:
q = lambda x: 8*x**2 + 8*x + 3

In [15]:
p(9) - q(9)

-68

In [16]:
p(9) + 7*q(9)

5716

In [2]:
u = np.array([5,3,2])
v = np.array([6,5,8])
u.dot(v)

61

In [5]:
u = np.array([6,2,6])

In [6]:
np.sqrt(u.dot(u))

8.717797887081348

In [7]:
np.linalg.norm(u)

8.717797887081348

In [8]:
A = np.array([[3, 1], [1, 5]])

In [9]:
x = np.array([1, 0])
(x.dot(A)).dot(x)

3

In [10]:
x = np.array([0, 1])
(x.dot(A)).dot(x)

5

In [11]:
u = np.array([8,8])
v = np.array([7,9])

In [12]:
u.dot(A).dot(v) - v.dot(A).dot(u)

0

In [13]:
u = np.array([2,2])
v = np.array([6,3])
w = np.array([9,8])

In [14]:
(8*u + v).dot(A).dot(w) - (8*u.dot(A).dot(w) + v.dot(A).dot(w))

0

In [2]:
from sympy import integrate, log, exp
from sympy.abc import x

In [2]:
integrate((8*x**2 + 3)*(8*x**2 + 3), (x, 0, 1))

189/5

In [3]:
integrate((7*exp(6*x))*(7*exp(6*x)), (x, 0, 1))

-49/12 + 49*exp(12)/12

In [3]:
import math
-49/12 + 49*math.exp(12)/12

664577.9816275993

In [8]:
integrate((5*x + 2)*(3*x**2), (x, 0, 1))

23/4

In [9]:
integrate((3*x**2)*(5*x + 2), (x, 0, 1))

23/4

In [3]:
integrate((5*exp(3*x))*(5*exp(3*x)), (x, 0, 1))

-25/6 + 25*exp(6)/6

In [6]:
math.sqrt(-25/6 + 25*math.exp(6)/6)

40.94858531809204

In [7]:
f = lambda x: 7*x + 4
g = lambda x: 3*x
h = lambda x: -x**2

In [9]:
x = 7
y = 5

In [10]:
f(x + y) - (f(x) + f(y))

-4

In [11]:
f(7*x) - 7*f(x)

-24

In [12]:
g(x + y) - (g(x) + g(y))

0

In [13]:
g(2*x) - 2*g(x)

0

In [14]:
h(x + y) - (h(x) + h(y))

-70

In [21]:
f = lambda u: u[0] + u[1] + 6
g = lambda u: u.dot(u)

In [22]:
u = np.array([9,4])
v = np.array([7,3])
w1=0.2
w2=0.8
f(w1*u + w2*v) - (w1*f(u) + w2*f(v))

0.0

In [20]:
g(w1*u + w2*v) - (w1*g(u) + w2*g(v))

-0.8000000000000114

In [12]:
e1 = (1/np.sqrt(2))*np.ones(2)
e2 = (1/np.sqrt(2))*np.array([-1, 1])

In [13]:
u = np.array([5, 7])

In [14]:
a = e1.dot(u)

In [15]:
b = e2.dot(u)

In [16]:
u - (a*e1 + b*e2)

array([0.00000000e+00, 1.77635684e-15])

In [17]:
print(a, b)

8.48528137423857 1.4142135623730945


In [18]:
e1 = np.array([1, 0])
e2 = np.array([1, 1])
u = np.array([6, 9])
u.dot(e1)*e1 + u.dot(e2)*e2

array([21, 15])

In [5]:
e1 = np.array([2, 2])
e2 = np.array([5, 9])

et1 = e1/np.linalg.norm(e1)
eh2 = e2 - e2.dot(et1)*et1
et2 = eh2/np.linalg.norm(eh2)

print(et1, eh2, et2)
print(np.linalg.norm(et1)**2)
print(np.linalg.norm(et2)**2)
print(et1.dot(et2))

[0.70710678 0.70710678] [-2.  2.] [-0.70710678  0.70710678]
0.9999999999999998
0.9999999999999998
4.440892098500626e-16


In [8]:
np.linalg.det([[2, 4], [2, 4]])

0.0

In [9]:
np.linalg.det([[2, 2], [4, 4]])

0.0

In [10]:
np.array([2, 2]).dot(np.array([8, 4]))

24

In [11]:
np.array([4, 4]).dot(np.array([8, 4]))

48

In [12]:
A = np.array([[5, 8], [-8, 5]])
b = np.array([3, 8])
np.linalg.solve(A, b)

array([-0.5505618 ,  0.71910112])

In [16]:
np.roots([8, 68, 574])

array([-4.25+7.32717544j, -4.25-7.32717544j])